name: Deploy to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: "18"
        cache: "npm"
    - run: npm install
    - run: npm run build-editor
    - run: npm run build-viewer
    - uses: actions/configure-pages@main
    - uses: actions/upload-pages-artifact@main
      with:
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - id: deployment
      uses: actions/deploy-pages@main